/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormConfirmDeleteOperator: typeof import('./src/components/forms/FormConfirmDeleteOperator.vue')['default']
    FormConfirmUbahAksesOperator: typeof import('./src/components/forms/FormConfirmUbahAksesOperator.vue')['default']
    FormEditLaporanBilling: typeof import('./src/components/forms/FormEditLaporanBilling.vue')['default']
    FormEksporData: typeof import('./src/components/forms/FormEksporData.vue')['default']
    FormPilihDateRange: typeof import('./src/components/forms/FormPilihDateRange.vue')['default']
    FormResetPasswordOperator: typeof import('./src/components/forms/FormResetPasswordOperator.vue')['default']
    FormTambahLogistik: typeof import('./src/components/forms/FormTambahLogistik.vue')['default']
    FormTambahMeja: typeof import('./src/components/forms/FormTambahMeja.vue')['default']
    FormTambahOperator: typeof import('./src/components/forms/FormTambahOperator.vue')['default']
    FormTambahPaketSewa: typeof import('./src/components/forms/FormTambahPaketSewa.vue')['default']
    FormTambahPengeluaran: typeof import('./src/components/forms/FormTambahPengeluaran.vue')['default']
    FormTambahPS: typeof import('./src/components/forms/FormTambahPS.vue')['default']
    FormTambahSewa: typeof import('./src/components/forms/FormTambahSewa.vue')['default']
    FormUbahHargaPaketSewa: typeof import('./src/components/forms/FormUbahHargaPaketSewa.vue')['default']
    FormUbahHargaProdukLogistik: typeof import('./src/components/forms/FormUbahHargaProdukLogistik.vue')['default']
    FormUbahNamaOperator: typeof import('./src/components/forms/FormUbahNamaOperator.vue')['default']
    FormUbahNamaPaketSewa: typeof import('./src/components/forms/FormUbahNamaPaketSewa.vue')['default']
    FormUbahNamaProdukLogistik: typeof import('./src/components/forms/FormUbahNamaProdukLogistik.vue')['default']
    FormUbahTarifPS: typeof import('./src/components/forms/FormUbahTarifPS.vue')['default']
    FormUpdatePengeluaran: typeof import('./src/components/forms/FormUpdatePengeluaran.vue')['default']
    FormUpdateSewa: typeof import('./src/components/forms/FormUpdateSewa.vue')['default']
    GeneralConfirmForm: typeof import('./src/components/forms/GeneralConfirmForm.vue')['default']
    LoginDialog: typeof import('./src/components/dialogs/LoginDialog.vue')['default']
    MejaMain: typeof import('./src/components/MejaMain.vue')['default']
    PlaystationIcon: typeof import('./src/components/icons/PlaystationIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
